default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: portland_tech_guide_development

test:
  <<: *default
  database: portland_tech_guide_test

production:
  <<: *default
  database: portland_tech_guide_production
  username: portland_tech_guide
  password: <%= ENV['PORTLAND_TECH_GUIDE_DATABASE_PASSWORD'] %>
